### ISSUE TITLE
Stuck on GUI

### ISSUE THREAD

**Issue by fhxserver** [BerkanYildiz/UCS#41]
Hello, why every time I use the GUI or console always stuck here? Please repaired.

SEE : http://image.prntscr.com/image/e681f33033584346950b6647026e288b.jpg

**Comment by ADeltaX** [comment]
Did you tried to start in console mode first? (edit config.ucs > guimode on false).
The gui hangs if there are a lot of players in db (I'm searching for a fix)

**Comment by smartclash** [comment]
@ADeltaX I WOULD RECOMMENDED YOU TO ALLOW USERS wheTHER  UCS CAN CHECK FOR PLAYERS IN GUI DURING START UP OR NOT IN THE CONFIG FILE

**Comment by ADeltaX** [comment]
@fhxserver Can you add me on skype? (adeltaxsystem) I would like to investigate the problem.

@smartclash Well, checks for players?

**Comment by fhxserver** [comment]
@ADeltaX You Already I add diskype friendship. Please confirmed.

The point I have a lot of players and a database of almost three million queries. But when I wipe and restart, the new 47k emulator query is already heavy to get started. whether it can be explained ?

**Comment by smartclash** [comment]
@fhxserver Okay, i found the issue. The gui actually starts to count number if players in database before starting up. As you said you have many people, the UCS takes time to query all the users. I would recommend you to use the console mode rather than using the GUI.

@ADeltaX As I said, you can simply add a true or false config in the config file whether to query users before starting. And may i know what is the default time for auto restart?
